### ISSUE TITLE
Missing default recipes

### ISSUE THREAD

**Issue by RIExJonny** [BlakeBr0/IronJetpacks#100]
**Describe the bug**

 there is no  recipes on how to make the coils

**To Reproduce**

fix the recipes

**Expected behavior**

should be able to craft the coils that is used to make the jetpacks

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:  ATM10 just added ironjetpacks and there is no recipes on the coils that is part of making the jetpacks

 - Forge:
 - Cucumber:
 - Iron Jetpacks:
 - Singleplayer or Multiplayer:

**Comment by RIExJonny** [comment]
https://github.com/user-attachments/assets/2f5318e6-6e99-4d56-8960-7357ce866370

**Comment by C00P2009** [comment]
Same issue

**Comment by LordCorellon** [comment]
I made a KubeJS file that will fix the issue, I'm not very good with KubeJS and more so since the changes from 1.21 so I couldn't figure out how to remove the old broken recipes (since the jetpacks don't upgrade, Wood->Stone still gives Wood jetpack back) so you now need to add a stick to the recipe below the jetpack.
 
[Iron Jetpacks.zip](https://github.com/user-attachments/files/16738474/Iron.Jetpacks.zip)

**Comment by RIExJonny** [comment]
thanks Lordcorellon but that wont fix atm10 for everyone so it need to be fixed the right way and for others also.

**Comment by RIExJonny** [comment]
also the leather strap is the same way.. cant be crafted

**Comment by LordCorellon** [comment]
> thanks Lordcorellon but that wont fix atm10 for everyone so it need to be fixed the right way and for others also.

Actually if you put the kubeJS script into the server-scripts folder it will fix it, at least until the Mod author can fix the built in recipes, it also fixes the straps too BTW.

Guess While I'm at it I would mention that there are several "Dead end" recipes that can't be upgraded, such as Iron jetpacks (Such an irony because of the Mod's name) is stuck at that tier as only the Stone can upgrade to Silver and only Silver to Platinum (Diamond Jetpacks are another "Dead end")

**Comment by LordCorellon** [comment]
@BlakeBr0 I saw the release notes fixed the missing recipes for the coil and the straps but I didn't see anything noting a fix for the jetpack recipes.

I just tried in-game with the latest release and using a wood jetpack with 2x stone thrusters, 4x stone and 1 stone capacitor still gives a wood jetpack back instead of upgrading to a stone jetpack.  Same issue persists though stone, silver, steel, platinum and emerald.

**Comment by BlakeBr0** [comment]
Damn, fixed in 8.0.2.

**Comment by LordCorellon** [comment]
So fast! Thanks.

Absolutely love your work, it's a real game changer.  Thanks for all your efforts

**Comment by RIExJonny** [comment]
thank you so much and keep up the good work . thanks for everything you do
