### ISSUE TITLE
Request: Increase Armor for Higher Tiers

### ISSUE THREAD

**Issue by cyberdragon442** [BlakeBr0/IronJetpacks#20]
It would be nice to have things as expensive as the diamond and emerald jetpacks have more than just 4 armor points (worse than an iron chestplate).

EDIT: I mean have the armor actually tiered with the tier rather than just the general config.

EDIT 2: Alternatively, emerald jetpack could be used to craft expensive powered armor (like the jetplates in Simply Jetpacks)

**Comment by BlakeBr0** [comment]
You can always change the armor values in the jetpack jsons, see:
https://mods.blakebr0.com/docs/ironjetpacks/jetpack-json

The reason they are low by default is because they are supposed to have a downside. If they were just as good as regular armor they would just be objectively better in every scenario which is lame.
